#!/bin/bash

if [ $UID != 0 ]
then
  echo "Please run this script with sudo: sudo $0"
  exit 1
fi

echo "Dependencies"
apt-get update
apt-get install build-essential
apt-get remove glpk
apt-get remove libglpk-dev
apt-get remove libglpk0
sudo -u $SUDO_USER wget -O glpk-4.55.tar.gz http://ftp.gnu.org/gnu/glpk/glpk-4.55.tar.gz
sudo -u $SUDO_USER tar -xvhf glpk-4.55.tar.gz
cd glpk-4.55
./configure
make
make install
cd ..
apt-get install libglpk-dev
apt-get install libglpk0
apt-get install bison
sudo -u $SUDO_USER wget -O bison-3.0.2.tar.gz http://ftp.gnu.org/gnu/bison/bison-3.0.2.tar.gz
sudo -u $SUDO_USER tar -xhvf bison-3.0.2.tar.gz
cd bison-3.0.2
./configure
make
make install
cd ..
apt-get install flex
apt-get install python-dev
apt-get install python-ply
apt-get install python-matplotlib
apt-get install python-gtk2
apt-get install pkg-config
apt-get install autoconf
apt-get install python-pip
apt-get install libppl0.11-dev
apt-get install libppl9
apt-get install ligppl
apt-get install ppl-dev
apt-get install libgmp10
apt-get install gnuplot
apt-get install python-gnuplot
apt-get install python-sympy
apt-get build-dep python-lxml
pip install lxml
pip install psutil

sudo -u $SUDO_USER wget -O pyglpk.zip http://publish.illinois.edu/c2e2-tool/files/2014/10/pyglpk.zip
sudo -u $SUDO_USER unzip -q pyglpk
cd pyglpk && make && make install
