#!/bin/bash

APT_IN="apt-get install -y"
APT_IN_NR="apt-get install -y --no-install-recommends"

if [ $UID != 0 ]
then
  echo "Please run this script with sudo: sudo $0"
  exit 1
fi

echo "Dependencies"
apt-get update
apt-get install -y build-essential
apt-get remove glpk
apt-get remove libglpk-dev
apt-get remove libglpk0
sudo -u $SUDO_USER wget -O glpk-4.55.tar.gz http://ftp.gnu.org/gnu/glpk/glpk-4.55.tar.gz
sudo -u $SUDO_USER tar -xvhf glpk-4.55.tar.gz
cd glpk-4.55
./configure
make
make install
cd ..
apt-get install -y libglpk-dev
apt-get install -y libglpk0
apt-get install -y bison
sudo -u $SUDO_USER wget -O bison-3.0.2.tar.gz http://ftp.gnu.org/gnu/bison/bison-3.0.2.tar.gz
sudo -u $SUDO_USER tar -xhvf bison-3.0.2.tar.gz
cd bison-3.0.2
./configure
make
make install
cd ..
apt-get install -y flex
apt-get install -y python-dev
apt-get install -y python-ply
apt-get install -y python-matplotlib
apt-get install -y python-gtk2
apt-get install -y pkg-config
apt-get install -y autoconf
apt-get install -y python-pip
apt-get install -y libppl0.11-dev
apt-get install -y libppl9
apt-get install -y ligppl
apt-get install -y ppl-dev
apt-get install -y libgmp10
apt-get install -y gnuplot
apt-get install -y python-gnuplot
$APT_IN_NR python-sympy
apt-get install -y libxslt1-dev
apt-get install libboost1.58-all-dev 

apt-get install python-lxml
pip install lxml
pip install psutil

sudo -u $SUDO_USER wget -O pyglpk.zip http://publish.illinois.edu/c2e2-tool/files/2014/10/pyglpk.zip
sudo -u $SUDO_USER unzip -q pyglpk
cd pyglpk && make && make install

#Removes compressed files
cd ../
rm *.tar.gz
rm *.zip
