#!/bin/sh
echo "This is a Test script to verify your C2E2's Functionality."
echo "If your C2E2 install properly, These five test cases should all pass"
echo "If only one test cases failed while other passes, please run test again to make sure"
echo "This test will run around 1 minute"
echo "Test1, Bruss"
cd Hylink
python terminal.py 0 bruss.hyxml > ../wd/Verbose 2> ../wd/warnings 
python c2e2testchecker.py goldenbruss
cd ../
cd wd
rm ReachSetProperty1
cd ../


echo "Test2, Linthermo"
cd Hylink
python terminal.py 1 linThermo.hyxml > ../wd/Verbose 2> ../wd/warnings 
python c2e2testchecker.py goldenlinthermo
cd ../
cd wd
rm ReachSetProperty1
cd ../

echo "Test3, MG"
cd Hylink
python terminal.py 0 MooreGreitzer.hyxml > ../wd/Verbose 2> ../wd/warnings 
python c2e2testchecker.py goldenmg
cd ../
cd wd
rm ReachSetProperty1
cd ../

echo "Test4, navSafe"
cd Hylink
python terminal.py 1 navUnsafe.hyxml > ../wd/Verbose 2> ../wd/warnings 
python c2e2testchecker.py goldennavsafe
cd ../
cd wd
rm ReachSetProperty1
cd ../
