#!/bin/sh
echo "first parameter is $1"
echo Compiling CAPD files to generate Simulator

if [ "$1" -eq "2" ]
then
	echo "Use CAPD"
	g++ -w -O2 simulator.cpp -o simu `../capd/bin/capd-config --cflags --libs`
else
	echo "Use ODEINT"
	g++ -w -O2 -std=c++11 simulator.cpp -o simu
fi

g++ -w -O2 guardGen.cpp -o guards `../capd/bin/capd-config --cflags --libs`
g++ -w -O2 Invcheck.cpp -o invariants `../capd/bin/capd-config --cflags --libs`
g++ -fPIC -shared hybridSimGI.cpp -o libhybridsim.so
echo Executables from CAPD generated, Verification process starts
#sh ./C2E2 < capdsimannot
