#!/bin/sh
if [ "$1" -eq "2" ]
then
	echo "Use CAPD"
	g++ -w -O2 simulator.cpp -o simu `../capd/bin/capd-config --cflags --libs`
else
	echo "Use ODEINT"
	g++ -w -O2 -std=c++11 simulator.cpp -o simu
fi
