#!/bin/sh
if [ "$1" -eq "2" ]
then
	echo Using CAPD.
	g++ -w -O2 simulator.cpp -o simu `../capd/bin/capd-config --cflags --libs` &
else
	echo Using ODEINT.
	g++ -w -O2 -std=c++11 simulator.cpp -o simu &
fi

echo Compiling guard/invariant files.
g++ -fPIC -shared hybridSimGI.cpp -o libhybridsim.so -lppl -lgmp &
g++ -fPIC -shared bloatedSimGI.cpp -o libbloatedsim.so -lppl -lgmp &
wait
echo Executables generated.
